<?php

declare(strict_types=1);

/*
 * PayQuickerSDK
 *
 * This file was automatically generated for PayQuicker by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PayQuickerSDKLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Namespace used to identify and refer to the object
 */
class WebhookNamespaces
{
    public const BANKACCOUNTS_CREATED = 'BANKACCOUNTS.CREATED';

    public const BANKACCOUNTS_UPDATED_DETAILS_MODIFIED = 'BANKACCOUNTS.UPDATED.DETAILS.MODIFIED';

    public const BANKACCOUNTS_UPDATED_STATUS_APPROVED = 'BANKACCOUNTS.UPDATED.STATUS.APPROVED';

    public const BANKACCOUNTS_UPDATED_STATUS_COMPLIANCEHOLD = 'BANKACCOUNTS.UPDATED.STATUS.COMPLIANCEHOLD';

    public const BANKACCOUNTS_UPDATED_STATUS_DELETED = 'BANKACCOUNTS.UPDATED.STATUS.DELETED';

    public const PAPERCHECKS_CREATED = 'PAPERCHECKS.CREATED';

    public const PAPERCHECKS_UPDATED_DETAILS_MODIFIED = 'PAPERCHECKS.UPDATED.DETAILS.MODIFIED';

    public const PAPERCHECKS_UPDATED_STATUS_CANCELLED = 'PAPERCHECKS.UPDATED.STATUS.CANCELLED';

    public const PAPERCHECKS_UPDATED_STATUS_INPROGRESS = 'PAPERCHECKS.UPDATED.STATUS.INPROGRESS';

    public const PAPERCHECKS_UPDATED_STATUS_REDEEMED = 'PAPERCHECKS.UPDATED.STATUS.REDEEMED';

    public const PAYMENTQUOTES_ACCEPTED = 'PAYMENTQUOTES.ACCEPTED';

    public const PAYMENTQUOTES_CANCELLED = 'PAYMENTQUOTES.CANCELLED';

    public const PAYMENTQUOTES_CREATED = 'PAYMENTQUOTES.CREATED';

    public const PAYMENTQUOTES_VOIDED = 'PAYMENTQUOTES.VOIDED';

    public const PREPAIDCARDS_CREATED = 'PREPAIDCARDS.CREATED';

    public const PREPAIDCARDS_UPDATED_STATUS_ACTIVE = 'PREPAIDCARDS.UPDATED.STATUS.ACTIVE';

    public const PREPAIDCARDS_UPDATED_STATUS_CLOSED = 'PREPAIDCARDS.UPDATED.STATUS.CLOSED';

    public const PREPAIDCARDS_UPDATED_STATUS_CLOSEDEXPIRED = 'PREPAIDCARDS.UPDATED.STATUS.CLOSEDEXPIRED';

    public const PREPAIDCARDS_UPDATED_STATUS_CLOSEDFRAUD = 'PREPAIDCARDS.UPDATED.STATUS.CLOSEDFRAUD';

    public const PREPAIDCARDS_UPDATED_STATUS_CLOSEDLOST = 'PREPAIDCARDS.UPDATED.STATUS.CLOSEDLOST';

    public const PREPAIDCARDS_UPDATED_STATUS_CLOSEDSTOLEN = 'PREPAIDCARDS.UPDATED.STATUS.CLOSEDSTOLEN';

    public const PREPAIDCARDS_UPDATED_STATUS_COMPLIANCEHOLD = 'PREPAIDCARDS.UPDATED.STATUS.COMPLIANCEHOLD';

    public const PREPAIDCARDS_UPDATED_STATUS_PENDINGACTIVATION = 'PREPAIDCARDS.UPDATED.STATUS.PENDINGACTIVATION';

    public const PREPAIDCARDS_UPDATED_STATUS_PENDINGORDER = 'PREPAIDCARDS.UPDATED.STATUS.PENDINGORDER';

    public const PREPAIDCARDS_UPDATED_STATUS_PENDINGRELEASE = 'PREPAIDCARDS.UPDATED.STATUS.PENDINGRELEASE';

    public const PREPAIDCARDS_UPDATED_STATUS_SUSPENDED = 'PREPAIDCARDS.UPDATED.STATUS.SUSPENDED';

    public const RECEIPTS_CREATED = 'RECEIPTS.CREATED';

    public const RECEIPTS_UPDATED_DETAILS_MODIFIED = 'RECEIPTS.UPDATED.DETAILS.MODIFIED';

    public const RECEIPTS_UPDATED_STATUS_CANCELLED = 'RECEIPTS.UPDATED.STATUS.CANCELLED';

    public const RECEIPTS_UPDATED_STATUS_COMPLETED = 'RECEIPTS.UPDATED.STATUS.COMPLETED';

    public const RECEIPTS_UPDATED_STATUS_EXPIRED = 'RECEIPTS.UPDATED.STATUS.EXPIRED';

    public const RECEIPTS_UPDATED_STATUS_FAILED = 'RECEIPTS.UPDATED.STATUS.FAILED';

    public const RECEIPTS_UPDATED_STATUS_PENDING = 'RECEIPTS.UPDATED.STATUS.PENDING';

    public const RECEIPTS_UPDATED_STATUS_PROCESSING = 'RECEIPTS.UPDATED.STATUS.PROCESSING';

    public const RECEIPTS_UPDATED_STATUS_REFUNDED = 'RECEIPTS.UPDATED.STATUS.REFUNDED';

    public const RECEIPTS_UPDATED_STATUS_RETURNED = 'RECEIPTS.UPDATED.STATUS.RETURNED';

    public const RECEIPTS_UPDATED_STATUS_REVERSED = 'RECEIPTS.UPDATED.STATUS.REVERSED';

    public const RECEIPTS_UPDATED_STATUS_REVIEWREQUIRED = 'RECEIPTS.UPDATED.STATUS.REVIEWREQUIRED';

    public const RECEIPTS_UPDATED_STATUS_SCHEDULED = 'RECEIPTS.UPDATED.STATUS.SCHEDULED';

    public const SPENDBACKQUOTES_ACCEPTED = 'SPENDBACKQUOTES.ACCEPTED';

    public const SPENDBACKQUOTES_CANCELLED = 'SPENDBACKQUOTES.CANCELLED';

    public const SPENDBACKQUOTES_CREATED = 'SPENDBACKQUOTES.CREATED';

    public const SPENDBACKQUOTES_VOIDED = 'SPENDBACKQUOTES.VOIDED';

    public const TRANSFERQUOTES_ACCEPTED = 'TRANSFERQUOTES.ACCEPTED';

    public const TRANSFERQUOTES_CANCELLED = 'TRANSFERQUOTES.CANCELLED';

    public const TRANSFERQUOTES_CREATED = 'TRANSFERQUOTES.CREATED';

    public const TRANSFERQUOTES_VOIDED = 'TRANSFERQUOTES.VOIDED';

    public const USEREVENTS_COMPLETED = 'USEREVENTS.COMPLETED';

    public const USEREVENTS_STARTED = 'USEREVENTS.STARTED';

    public const USEREVENTS_UPDATED = 'USEREVENTS.UPDATED';

    public const USERS_CREATED = 'USERS.CREATED';

    public const USERS_UPDATED_IDV_FAILED = 'USERS.UPDATED.IDV.FAILED';

    public const USERS_UPDATED_IDV_PASSED = 'USERS.UPDATED.IDV.PASSED';

    public const USERS_UPDATED_KYC_APPROVED = 'USERS.UPDATED.KYC.APPROVED';

    public const USERS_UPDATED_KYC_PROVIDED = 'USERS.UPDATED.KYC.PROVIDED';

    public const USERS_UPDATED_KYC_REJECTED = 'USERS.UPDATED.KYC.REJECTED';

    public const USERS_UPDATED_KYC_REQUIRED = 'USERS.UPDATED.KYC.REQUIRED';

    public const USERS_UPDATED_STATUS_REGISTRATIONCOMPLETE = 'USERS.UPDATED.STATUS.REGISTRATIONCOMPLETE';

    public const USERS_UPDATED_STATUS_REGISTRATIONINPROGRESS = 'USERS.UPDATED.STATUS.REGISTRATIONINPROGRESS';

    public const ELECTRONICWALLETS_CREATED = 'ELECTRONICWALLETS.CREATED';

    public const ELECTRONICWALLETS_UPDATED_DETAILS_MODIFIED = 'ELECTRONICWALLETS.UPDATED.DETAILS.MODIFIED';

    public const ELECTRONICWALLETS_UPDATED_STATUS_APPROVED = 'ELECTRONICWALLETS.UPDATED.STATUS.APPROVED';

    public const ELECTRONICWALLETS_UPDATED_STATUS_COMPLIANCEHOLD = 'ELECTRONICWALLETS.UPDATED.STATUS.COMPLIANCEHOLD';

    public const ELECTRONICWALLETS_UPDATED_STATUS_DELETED = 'ELECTRONICWALLETS.UPDATED.STATUS.DELETED';

    public const UNKNOWN = 'UNKNOWN';

    private const _ALL_VALUES = [
        self::BANKACCOUNTS_CREATED,
        self::BANKACCOUNTS_UPDATED_DETAILS_MODIFIED,
        self::BANKACCOUNTS_UPDATED_STATUS_APPROVED,
        self::BANKACCOUNTS_UPDATED_STATUS_COMPLIANCEHOLD,
        self::BANKACCOUNTS_UPDATED_STATUS_DELETED,
        self::PAPERCHECKS_CREATED,
        self::PAPERCHECKS_UPDATED_DETAILS_MODIFIED,
        self::PAPERCHECKS_UPDATED_STATUS_CANCELLED,
        self::PAPERCHECKS_UPDATED_STATUS_INPROGRESS,
        self::PAPERCHECKS_UPDATED_STATUS_REDEEMED,
        self::PAYMENTQUOTES_ACCEPTED,
        self::PAYMENTQUOTES_CANCELLED,
        self::PAYMENTQUOTES_CREATED,
        self::PAYMENTQUOTES_VOIDED,
        self::PREPAIDCARDS_CREATED,
        self::PREPAIDCARDS_UPDATED_STATUS_ACTIVE,
        self::PREPAIDCARDS_UPDATED_STATUS_CLOSED,
        self::PREPAIDCARDS_UPDATED_STATUS_CLOSEDEXPIRED,
        self::PREPAIDCARDS_UPDATED_STATUS_CLOSEDFRAUD,
        self::PREPAIDCARDS_UPDATED_STATUS_CLOSEDLOST,
        self::PREPAIDCARDS_UPDATED_STATUS_CLOSEDSTOLEN,
        self::PREPAIDCARDS_UPDATED_STATUS_COMPLIANCEHOLD,
        self::PREPAIDCARDS_UPDATED_STATUS_PENDINGACTIVATION,
        self::PREPAIDCARDS_UPDATED_STATUS_PENDINGORDER,
        self::PREPAIDCARDS_UPDATED_STATUS_PENDINGRELEASE,
        self::PREPAIDCARDS_UPDATED_STATUS_SUSPENDED,
        self::RECEIPTS_CREATED,
        self::RECEIPTS_UPDATED_DETAILS_MODIFIED,
        self::RECEIPTS_UPDATED_STATUS_CANCELLED,
        self::RECEIPTS_UPDATED_STATUS_COMPLETED,
        self::RECEIPTS_UPDATED_STATUS_EXPIRED,
        self::RECEIPTS_UPDATED_STATUS_FAILED,
        self::RECEIPTS_UPDATED_STATUS_PENDING,
        self::RECEIPTS_UPDATED_STATUS_PROCESSING,
        self::RECEIPTS_UPDATED_STATUS_REFUNDED,
        self::RECEIPTS_UPDATED_STATUS_RETURNED,
        self::RECEIPTS_UPDATED_STATUS_REVERSED,
        self::RECEIPTS_UPDATED_STATUS_REVIEWREQUIRED,
        self::RECEIPTS_UPDATED_STATUS_SCHEDULED,
        self::SPENDBACKQUOTES_ACCEPTED,
        self::SPENDBACKQUOTES_CANCELLED,
        self::SPENDBACKQUOTES_CREATED,
        self::SPENDBACKQUOTES_VOIDED,
        self::TRANSFERQUOTES_ACCEPTED,
        self::TRANSFERQUOTES_CANCELLED,
        self::TRANSFERQUOTES_CREATED,
        self::TRANSFERQUOTES_VOIDED,
        self::USEREVENTS_COMPLETED,
        self::USEREVENTS_STARTED,
        self::USEREVENTS_UPDATED,
        self::USERS_CREATED,
        self::USERS_UPDATED_IDV_FAILED,
        self::USERS_UPDATED_IDV_PASSED,
        self::USERS_UPDATED_KYC_APPROVED,
        self::USERS_UPDATED_KYC_PROVIDED,
        self::USERS_UPDATED_KYC_REJECTED,
        self::USERS_UPDATED_KYC_REQUIRED,
        self::USERS_UPDATED_STATUS_REGISTRATIONCOMPLETE,
        self::USERS_UPDATED_STATUS_REGISTRATIONINPROGRESS,
        self::ELECTRONICWALLETS_CREATED,
        self::ELECTRONICWALLETS_UPDATED_DETAILS_MODIFIED,
        self::ELECTRONICWALLETS_UPDATED_STATUS_APPROVED,
        self::ELECTRONICWALLETS_UPDATED_STATUS_COMPLIANCEHOLD,
        self::ELECTRONICWALLETS_UPDATED_STATUS_DELETED,
        self::UNKNOWN
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for WebhookNamespaces.");
    }
}
